# sudo: true

language: python

python:
    - "3.7"
    - "3.8"

before_install:
    - "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_PREVIEW=1 python"
    - "source $HOME/.poetry/env"
    - "poetry --version"

install:
    - "poetry install"

# before_script:

script:
    - "pytest -vv"

# after_scrit:

# after_success:

# after_failure:

branches:
  only:
    - /.*/

notifications:
  email:
    on_success: never
